/*
###############################################################
#  Generated by:      Cadence Innovus 18.17-s055_1
#  OS:                Linux x86_64(Host ID 09vlab117.coe.neu.edu)
#  Generated on:      Sun Aug 10 22:45:45 2025
#  Design:            counter
#  Command:           saveNetlist counter/Innovus_new/counter.v
###############################################################
*/
module counter (
	clk, 
	rst, 
	out);
   input clk;
   input rst;
   output [3:0] out;

   // Internal wires
   wire N7;
   wire N8;
   wire N10;
   wire n1;
   wire n2;
   wire n3;
   wire n5;
   wire n6;
   wire n7;
   wire n8;
   wire n9;
   wire n10;
   wire n13;
   wire n14;
   wire n17;
   wire n18;

   DFFPOSX1 \out_reg[0]  (.CLK(clk),
	.D(n18),
	.Q(out[0]));
   DFFPOSX1 \out_reg[1]  (.CLK(clk),
	.D(N8),
	.Q(out[1]));
   DFFPOSX1 \out_reg[2]  (.CLK(clk),
	.D(n9),
	.Q(out[2]));
   DFFPOSX1 \out_reg[3]  (.CLK(clk),
	.D(N10),
	.Q(out[3]));
   XOR2X1 U10 (.A(out[1]),
	.B(out[0]),
	.Y(n6));
   AOI21X1 U12 (.A(n1),
	.B(n7),
	.C(n3),
	.Y(N10));
   AOI21X1 U14 (.A(out[2]),
	.B(n5),
	.C(n2),
	.Y(n8));
   INVX1 U15 (.A(out[2]),
	.Y(n17));
   AND2X1 U16 (.A(n10),
	.B(rst),
	.Y(n9));
   XNOR2X1 U17 (.A(n5),
	.B(n17),
	.Y(n10));
   INVX1 U20 (.A(n5),
	.Y(n14));
   NOR3X1 U21 (.A(n17),
	.B(out[3]),
	.C(n14),
	.Y(n13));
   INVX1 U22 (.A(n13),
	.Y(n7));
   OR2X1 U25 (.A(n3),
	.B(out[0]),
	.Y(N7));
   INVX1 U26 (.A(N7),
	.Y(n18));
   AND2X2 U27 (.A(out[1]),
	.B(out[0]),
	.Y(n5));
   INVX1 U28 (.A(n8),
	.Y(n1));
   AND2X1 U29 (.A(rst),
	.B(n6),
	.Y(N8));
   INVX1 U30 (.A(out[3]),
	.Y(n2));
   INVX1 U31 (.A(rst),
	.Y(n3));
endmodule

